changed close batch checker logic
0xPolygonHermez/zkevm-node pull request #1028
Opened 2022-08-10 13:32 UTC by Mikelle

Closes https://github.com/0xPolygonHermez/zkevm-node/issues/977
Closes https://github.com/0xPolygonHermez/zkevm-node/issues/975
Closes #1026

### What does this PR do?

Changed logic when seq is checking, should it close batch or not

### Reviewers

Main reviewers:

- @arnaubennassar

2022-08-10 16:02 UTC, arnaubennassar requested changes

2022-08-10 16:02 UTC, arnaubennassar commented on state/pgstatestorage.go
> +}
Not sure what's the purpose of this function, who is the consumer?

2022-08-10 16:08 UTC, arnaubennassar requested changes

2022-08-10 16:08 UTC, arnaubennassar commented on state/pgstatestorage.go
> +func (p *PostgresStorage) UpdateGERInOpenBatch(ctx context.Context, ger common.Hash, dbTx pgx.Tx) error {
Please add sanity check to ensure that the batch has no txs in it. And force `dbTx != nil`

2022-08-10 16:59 UTC, arnaubennassar commented on state/pgstatestorage.go
> +func (p *PostgresStorage) UpdateGERInOpenBatch(ctx context.Context, ger common.Hash, dbTx pgx.Tx) error {
Also, it would be nice to not only update the GER, but also the timestamp with `time.Now()`

2022-08-11 08:39 UTC, arnaubennassar approved these changes

2022-08-11 09:31 UTC, cool-develope commented on sequencer/batchbuilder.go
> +	blockNum, mainnetExitRoot, err := s.state.GetBlockNumAndMainnetExitRootByGER(ctx, s.sequenceInProgress.GlobalExitRoot, nil)
it should trigger `object not found` in the init stage.
`GlobalExitRoot = 0x0000...` there is no the related main_exit_root.

2022-08-11 09:31 UTC, cool-develope commented on sequencer/batchbuilder.go
> +	if lastGer.MainnetExitRoot != mainnetExitRoot {
```suggestion
	if lastGer.GlobalExitRoot !=  s.sequenceInProgress.GlobalExitRoot
```
I think the logic should like this...

2022-08-11 09:31 UTC, cool-develope commented on sequencer/batchbuilder.go
> +	blockNum, mainnetExitRoot, err := s.state.GetBlockNumAndMainnetExitRootByGER(ctx, s.sequenceInProgress.GlobalExitRoot, nil)
`2022-08-11T09:27:08Z    ERROR   sequencer/batchbuilder.go:248   failed to get mainnetExitRoot and blockNum by ger, err: object not found%!(EXTRA string=
/src/log/log.go:106 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:164 github.com/0xPolygonHermez/zkevm-node/log.Errorf()
/src/sequencer/batchbuilder.go:248 github.com/0xPolygonHermez/zkevm-node/sequencer.(*Sequencer).shouldCloseSequenceInProgress()
/src/sequencer/batchbuilder.go:29 github.com/0xPolygonHermez/zkevm-node/sequencer.(*Sequencer).tryToProcessTx()
/src/sequencer/sequencer.go:132 github.com/0xPolygonHermez/zkevm-node/sequencer.(*Sequencer).Start.func1()
)`

2022-08-11 10:18 UTC, cool-develope reviewed
Where is the test part?

2022-08-11 10:18 UTC, cool-develope commented on state/pgstatestorage.go
> +	err = e.QueryRow(ctx, isBatchHasTxsQuery).Scan(&isBatchHasTxs)
```suggestion
	err = e.QueryRow(ctx, isBatchHasTxsQuery, batchNumber).Scan(&isBatchHasTxs)
```

2022-08-11 10:22 UTC, cool-develope commented on state/pgstatestorage.go
> +	if isBatchHasTxs {
```suggestion
	if !isBatchHasTxs {
```

2022-08-11 14:29 UTC, cool-develope approved these changes

2022-08-11 14:38 UTC, arnaubennassar requested changes

2022-08-11 14:38 UTC, arnaubennassar commented on state/pgstatestorage.go
> +	const isBatchHasTxsQuery = `SELECT EXISTS (SELECT 1 FROM state.batch WHERE raw_txs_data IS NOT NULL AND batch_num = $1)`
`raw_txs_data` is only set once the batch is closed. The correct way of checking this is to check if there are l2blocks with the same batch number

2022-08-11 15:35 UTC, arnaubennassar approved these changes

2022-08-11 15:38 UTC, merged