Separate config file for testing and adapt makefile and compose files…
0xPolygonHermez/zkevm-node pull request #1068
Opened 2022-08-19 13:37 UTC by KonradIT

… to env var

Closes #1043.

### What does this PR do?

Config file for testing is stored in `test/` - instead of using the `.local.toml` files.

Makefile and docker-compose files share an env var to switch between these files.

### Reviewers

Main reviewers:

- @arnaubennassar 
- @Mikelle 

Codeowner reviewers:

2022-08-19 13:48 UTC, Mikelle approved these changes

2022-08-19 15:51 UTC, arnaubennassar requested changes
- Add specific config for the node (not only the prover) for testing
- Tweak node config
- Increase nTx in ethtransfer_test to 100

2022-08-23 13:49 UTC, KonradIT commented
The config for node *in test mode* is already tweaked to reduce the wait period for virtualization.

```diff
37c37
< LastBatchVirtualizationTimeMaxWaitPeriod = "300s"
---
> LastBatchVirtualizationTimeMaxWaitPeriod = "120s"
```

So is the timeout for the prover server:

```diff
28,29c28,29
<     "proverServerMockTimeout": 60000000,
< 
---
>     "proverServerMockTimeout": 10000000,
>     
```

2022-08-23 16:24 UTC, KonradIT commented
Note the 3 minute timeout decrease compared to `develop`!!

2022-08-24 07:29 UTC, arnaubennassar approved these changes

2022-08-24 07:30 UTC, merged