Feature/multiple txs by sequencer
0xPolygonHermez/zkevm-node pull request #1108
Opened 2022-08-31 12:10 UTC by Mikelle

Closes https://github.com/0xPolygonHermez/zkevm-node/issues/817

### What does this PR do?

Multiple txs in the sequence sent to the executor

### Reviewers

Main reviewers:

- @arnaubennassar

2022-08-31 15:29 UTC, arnaubennassar commented on sequencer/batchbuilder.go
> +		}
This last `else` statement is unnecessary, you can just put the log on top of `SumUpZkCounters`

2022-09-01 08:04 UTC, arnaubennassar requested changes
Make sure that the changes on config files [local, debug, test, defaults] are consistent

2022-09-12 16:23 UTC, arnaubennassar approved these changes

2022-09-13 07:51 UTC, ToniRamirezM approved these changes

2022-09-13 08:11 UTC, merged