Fix/#1119 tx invalid
0xPolygonHermez/zkevm-node pull request #1134
Opened 2022-09-08 08:45 UTC by ARR552

Closes #1119 

### What does this PR do?

This PR fixes the invalid txs in the pool.

### Reviewers

- @Mikelle 
- @arnaubennassar 
- @KonradIT

2022-09-08 13:40 UTC, arnaubennassar requested changes

2022-09-08 13:40 UTC, arnaubennassar commented on sequencer/batchbuilder.go
> +			log.Errorf("error closing sequence: %s", err.Error())
```suggestion
			log.Errorf("error closing sequence: %w", err)
```

2022-09-08 13:40 UTC, arnaubennassar commented on sequencer/batchbuilder.go
> +				log.Error("error loading sequence from state: %s", err.Error())
```suggestion
				log.Error("error loading sequence from state: %w", err)
```

2022-09-08 13:40 UTC, arnaubennassar commented on sequencer/batchbuilder.go
> +			return types.Sequence{}, fmt.Errorf("failed to begin state transaction to close batch, err: %s", err.Error())
```suggestion
			return types.Sequence{}, fmt.Errorf("failed to begin state transaction to close batch, err: %w", err)
```

2022-09-08 13:40 UTC, arnaubennassar commented on sequencer/batchbuilder.go
> +		return fmt.Errorf("failed to create new sequence, err: %s", err.Error())
Same for all the changes

2022-09-09 10:17 UTC, Mikelle approved these changes

2022-09-09 10:36 UTC, arnaubennassar approved these changes

2022-09-09 10:38 UTC, merged