Database Split
0xPolygonHermez/zkevm-node pull request #1155
Opened 2022-09-13 17:59 UTC by tclemos

Closes #649.

### What does this PR do?

Split the single DB into 3 new ones: State, Pool and RPC.

### Reviewers

Main reviewers:

@arnaubennassar
@ToniRamirezM 
@Mikelle 
@KonradIT 
@ARR552 
@cool-develope

2022-09-14 07:01 UTC, ARR552 approved these changes

2022-09-14 08:31 UTC, KonradIT approved these changes

2022-09-14 09:17 UTC, arnaubennassar requested changes
Great job :rocket:

2022-09-14 09:17 UTC, arnaubennassar commented on docker-compose.yml
> +      - ZKEVM_NODE_STATEDB_USER=state_user
Suggestion: this config is already defined in config files. We can rely on it instead of having it on the docker-compose

2022-09-14 10:05 UTC, Mikelle approved these changes

2022-09-14 11:48 UTC, ToniRamirezM approved these changes

2022-09-15 08:32 UTC, arnaubennassar approved these changes

2022-09-15 13:55 UTC, merged