Batchsender script
0xPolygonHermez/zkevm-node pull request #1366
Opened 2022-11-07 16:23 UTC by kind84

### Background

While developing the new aggregator, we would like to have a convenient way to issue batch transactions on layer 1 for testing purposes.
This means bypassing the sequencer and directly interact with L1.

### What does this PR do?

This PR proposes to add a `batchsender` script in `test/scripts` that accepts as argument the number of batches (one L1 transaction per batch) to be sent (it defaults to 1 batch when no arguments are passed).

It can be easily installed with `go install` to be used later or included in shell scripts.

Examples:
- Send 1 batch:
```sh
$  batcsender
```
- send 42 batches:
```sh
$ batchsender 42
```

### Reviewers

Main reviewers:

@ARR552 
@arnaubennassar

2022-11-08 14:34 UTC, arnaubennassar requested changes
I like this script, I think it's going to be useful :top:

Beyond the comments left in the review, I think that at this point it would be nice to have a `test/scripts/README.md` explaining what each script does and how they are used, otherwise it's going to be hard to remember... Of course you don't have to document all the existing scripts, but we should at least try to provide this for the ones that are not yet merged

2022-11-10 09:41 UTC, kind84 commented on test/scripts/batchsender/main.go
> +	}
good point @arnaubennassar, I switched to the `cli` package here 17b6eb46d5ab25e25fcecc6786bda29c0d892678

2022-11-10 09:41 UTC, kind84 commented on test/scripts/batchsender/main.go
> +		log.Info("Using address: ", seqAddr)
nice catch @arnaubennassar , fixed here 17b6eb46d5ab25e25fcecc6786bda29c0d892678

2022-11-10 09:44 UTC, kind84 commented
> I like this script, I think it's going to be useful top
> 
> Beyond the comments left in the review, I think that at this point it would be nice to have a `test/scripts/README.md` explaining what each script does and how they are used, otherwise it's going to be hard to remember... Of course you don't have to document all the existing scripts, but we should at least try to provide this for the ones that are not yet merged

@arnaubennassar I totally agree. I also propose to think about implementing a companion CLI app for development that could incorporate some of these scripts. If you agree I can try to set up a draft version.
For now I added the readme here 3654dfe638329717f0011260da16b34f200ce971.

2022-11-10 13:39 UTC, kind84 commented
I updated the script to allow for waiting batches to be verified on L1.
The only way that I came up with is to filter L1 logs in a similar way the Synchronizer does calling `etherman.GetRollupInfoByBlockRange`.
Please suggest if there is a better way to do that.

2022-11-10 16:16 UTC, arnaubennassar approved these changes

2022-11-11 07:39 UTC, Psykepro approved these changes

2022-11-14 11:04 UTC, merged