Review some logging levels in JSON-RPC component
0xPolygonHermez/zkevm-node pull request #1413
Opened 2022-11-23 12:25 UTC by KonradIT

Closes #1269

### What does this PR do?

Changed some logging levels to clean up the `error` timeline, and moved some `debug` logs to `info`.

### Reviewers

Main reviewers:

- @arnaubennassar 
- @tclemos 
- @ToniRamirezM 

Codeowner reviewers:

2022-11-23 12:27 UTC, KonradIT commented
### Todo:

- [ ] Find `panic` errors: Haven't found any in RPC side, the ones that exist are for tests, and should remain there
- [ ] More descriptive errors and better handling of pointer vars

2022-11-24 10:30 UTC, arnaubennassar requested changes

2022-11-24 10:30 UTC, arnaubennassar commented on ethtxmanager/ethtxmanager.go
> +			log.Infof("tx %s failed, err: %w", tx.Hash(), err)
this looks like an actual error

2022-11-24 12:47 UTC, arnaubennassar approved these changes

2022-11-28 16:41 UTC, merged