WaitTxToBeSynched
0xPolygonHermez/zkevm-node pull request #1418
Opened 2022-11-24 16:32 UTC by ToniRamirezM

Closes #1411 

### What does this PR do?

Adds a new state function to wait for a transaction to be synched.

### Reviewers

Main reviewers:

- @arnaubennassar 
- @KonradIT 
- @ARR552

2022-11-25 10:27 UTC, arnaubennassar requested changes
Looks good! It would be nice to add unit test for:
- WaitSequencingTxToBeSynched
- WaitVerifiedBatchToBeSynched

2022-11-25 10:31 UTC, ARR552 approved these changes

2022-11-25 10:50 UTC, kind84 approved these changes
LGTM, only a tiny note on the name, I think it `Synced` and not `Synched`, but it doesn't matter much :)

2022-11-28 14:59 UTC, arnaubennassar approved these changes

2022-11-28 15:47 UTC, merged