Fix erroneous return in VerifyBatches function
0xPolygonHermez/zkevm-node pull request #1441
Opened 2022-12-05 12:52 UTC by KonradIT

Reported by @cool-develope : https://github.com/0xPolygonHermez/zkevm-node/blob/develop/ethtxmanager/ethtxmanager.go#L153

### What does this PR do?

The function was returning `nil, nil` when everything goes right.

### Reviewers

Main reviewers:

- @cool-develope 
- @arnaubennassar 
- @ARR552 

Codeowner reviewers:

2022-12-05 13:41 UTC, cool-develope commented on ethtxmanager/ethtxmanager.go
> +			}
```suggestion
```

2022-12-05 13:47 UTC, kind84 requested changes

2022-12-05 13:47 UTC, kind84 commented on ethtxmanager/ethtxmanager.go
>  	return tx, nil
@KonradIT I think that we should return an error here if `tx` is nil.

2022-12-05 14:17 UTC, cool-develope approved these changes

2022-12-06 07:05 UTC, kind84 commented on ethtxmanager/ethtxmanager.go
>  	return tx, nil
Fixed here 87320ae2d738102cd969c53cdd88fa0a531c995b

2022-12-06 09:53 UTC, cool-develope commented on aggregator/aggregator.go
> +			log.Infof("Final proof for batches [%d-%d] verified in transaction [%v]", proof.BatchNumber, proof.BatchNumberFinal, tx.Hash().TerminalString())
Do you know why this part is not covered in the test?

2022-12-06 10:17 UTC, kind84 approved these changes

2022-12-06 10:18 UTC, merged