Gas limit 150K + tests
0xPolygonHermez/zkevm-node pull request #1551
Opened 2023-01-17 13:28 UTC by ARR552

Closes #1482 

### What does this PR do?

Adds a check to see if a claim tx has a gasLimit higher than 150K or 0 gasLimit.
Also fixes the unit tests

### Reviewers

- @arnaubennassar 
- @ToniRamirezM

2023-01-18 16:45 UTC, arnaubennassar requested changes

2023-01-18 16:45 UTC, arnaubennassar commented on pool/transaction.go
> +	freeClaimGasLimit uint64 = 150000
Please make this a config param, as the bridge SC may change

2023-01-20 14:53 UTC, tclemos approved these changes

2023-01-23 13:39 UTC, cool-develope approved these changes

2023-01-23 14:51 UTC, arnaubennassar approved these changes

2023-01-23 15:40 UTC, merged