add support to pre-EIP155 txs
0xPolygonHermez/zkevm-node pull request #1582
Opened 2023-01-24 13:34 UTC by tclemos

Closes #1536.

### What does this PR do?

add support to pre-EIP155 txs, which are txs signed without Chain ID

### Reviewers

Main reviewers:

@arnaubennassar 
@ToniRamirezM 
@ARR552

2023-01-24 16:41 UTC, cool-develope commented on state/crypto.go
> +	if tx.ChainId().Uint64() != 0 {
duplication of ` tx.ChainId().Uint64()`, it is preferred to assign a variable

2023-01-24 17:07 UTC, ToniRamirezM approved these changes

2023-01-25 13:30 UTC, cool-develope approved these changes

2023-01-26 08:16 UTC, ARR552 approved these changes
Just a name suggestion

2023-01-26 08:16 UTC, ARR552 commented on state/helper.go
> +	etherNewV = 35
```suggestion
	etherPre155V = 35
```

2023-01-26 09:16 UTC, arnaubennassar requested changes
It would eb nice to ru an E2E test to ensure that we work well with this kind of txs even when we get them through L1

2023-01-26 14:02 UTC, tclemos commented
> It would eb nice to ru an E2E test to ensure that we work well with this kind of txs even when we get them through L1

fair enough, let's do it

2023-01-26 14:45 UTC, tclemos commented
> It would eb nice to ru an E2E test to ensure that we work well with this kind of txs even when we get them through L1

@arnaubennassar e2e test added

2023-01-26 15:46 UTC, arnaubennassar requested changes

2023-01-26 15:46 UTC, arnaubennassar commented on test/e2e/preEIP155_test.go
> +	}
Could you add wait tx to be virtualized? no need for consolidated, but I want to be sure that we dont have any problem when unpacking the data from the sync

2023-01-27 08:57 UTC, arnaubennassar approved these changes

2023-01-27 08:58 UTC, merged