expose the monitoredtx struct
0xPolygonHermez/zkevm-node pull request #1793
Opened 2023-03-10 13:11 UTC by C001-developer

Ref https://github.com/0xPolygonHermez/zkevm-bridge-service/issues/334

### What does this PR do?

- Refactor the `monitoredtx` struct to use in the bridge repo
- Clean up some deprecated codes

### Reviewers

Main reviewers:

- @tclemos 
- @ARR552

2023-03-12 04:24 UTC, tclemos requested changes
monitoredTx has a reason to be private and must never be shared with external components, please, close this PR and let's talk about what you need in the bridge, so we can find a solution without having to break the component design.

2023-03-13 21:09 UTC, tclemos approved these changes

2023-03-14 07:37 UTC, ARR552 approved these changes

2023-03-14 10:01 UTC, ToniRamirezM approved these changes

2023-03-14 10:13 UTC, merged