fix: moving print for storing tx in finalizer.
0xPolygonHermez/zkevm-node pull request #1814
Opened 2023-03-14 07:28 UTC by Psykepro

Closes #1812

### What does this PR do?

Moving tx print for storing tx from `handleSuccessfulTxProcessResp` to `storeProcessedTx` where we already check if the tx is `nil` to return.

### Reviewers

- @ToniRamirezM
- @arnaubennassar 
- @agnusmor 

Main reviewers:

- @ToniRamirezM
- @arnaubennassar 

Codeowner reviewers:

- @ToniRamirezM

2023-03-14 09:32 UTC, ToniRamirezM approved these changes

2023-03-14 13:55 UTC, arnaubennassar commented
I still don't understand why we need to call a method named `handleSuccessfulTxProcessResp` that in return will call `storeProcessedTx` if we don't have a tx to store... Wouldn't it be better to just update the batch, without dealing with the concept of tx?

If you don't feel confortable doing this, it's ok, but I think that this is missleading and can introduce problems. Feel free to merge if you have already considered what I'm saying

2023-03-14 14:56 UTC, Psykepro commented
> I still don't understand why we need to call a method named `handleSuccessfulTxProcessResp` that in return will call `storeProcessedTx` if we don't have a tx to store... Wouldn't it be better to just update the batch, without dealing with the concept of tx?
> 
> If you don't feel confortable doing this, it's ok, but I think that this is missleading and can introduce problems. Feel free to merge if you have already considered what I'm saying

Okay will move the `storeProcessedTx` outside of the `handleSuccessfulTxProcessResp`.

2023-03-15 12:38 UTC, agnusmor approved these changes

2023-03-15 12:40 UTC, arnaubennassar requested changes

2023-03-15 12:40 UTC, arnaubennassar commented on sequencer/finalizer.go
> +	f.batch.stateRoot = result.NewStateRoot
Is this stored on the DB as well?

2023-03-15 13:38 UTC, arnaubennassar approved these changes

2023-03-16 07:18 UTC, ToniRamirezM approved these changes

2023-03-16 07:59 UTC, merged