remove unit suffix from duration config params
0xPolygonHermez/zkevm-node pull request #1927
Opened 2023-03-24 17:41 UTC by tclemos

Closes #1926.

### What does this PR do?

Fix duration parameters 

### Reviewers

Main reviewers:

@arnaubennassar 
@ToniRamirezM

2023-03-24 17:45 UTC, arnaubennassar requested changes

2023-03-24 17:45 UTC, arnaubennassar commented on config/environments/public/public.node.config.toml
> +WriteTimeout = "60"
```suggestion
ReadTimeout = "60s"
WriteTimeout = "60s"
```

2023-03-24 17:52 UTC, arnaubennassar approved these changes

2023-04-06 10:17 UTC, Psykepro approved these changes

2023-05-02 16:45 UTC, tclemos commented
closed due to #2068

2023-05-02 16:45 UTC, closed without merging