Change StateDB for HashDB
0xPolygonHermez/zkevm-node pull request #2070
Opened 2023-05-03 10:24 UTC by ToniRamirezM

Closes #2067

### What does this PR do?

Changes StateDB for HashDB

### Reviewers

Main reviewers:

- @ARR552 
- @agnusmor 
- @tclemos

2023-05-05 14:09 UTC, ARR552 approved these changes

2023-05-19 07:26 UTC, Psykepro requested changes

2023-05-19 07:26 UTC, Psykepro commented on sequencer/finalizer.go
> +	for len(f.pendingTransactionsToStore) > 0 {
Using a `WaitGroup` for waiting is way better than sleeping. As it could take less than 100 ms.

2023-05-19 10:51 UTC, Psykepro approved these changes

2023-05-25 22:17 UTC, agnusmor commented on sequencer/finalizer.go
> +	oneHundred = 100
I think this constant is not used. In the storePendingTransactions we are using the "100" value directly (with  //nolint:gomnd). Maybe we need to replace the "100" for this oneHundred const (or delete this const as is not used)

2023-05-25 22:17 UTC, agnusmor commented on sequencer/finalizer.go
> +	log.Info("waiting for pending transactions to be stored took: ", endWait.Sub(startWait).String())
it will be good to put in the message log the unit of the time (miliseconds(ms)?)

2023-06-20 13:52 UTC, ToniRamirezM commented
This changes are included in #2196

2023-06-20 13:52 UTC, closed without merging