Implement WebSocket Read Limit for Denial-of-Service Protection
0xPolygonHermez/zkevm-node pull request #2304
Opened 2023-07-19 10:42 UTC by Psykepro

Closes #2293.

### What does this PR do?

This PR addresses a potential vulnerability in our WebSocket server where it could be subjected to a Denial-of-Service (DoS) attack by sending continuous data, eventually causing the node to stop due to out-of-memory (OOM) errors.

By introducing a read limit on incoming WebSocket messages, we add a safeguard against such attacks without hindering our regular server operations. This PR involves:

1. Call the `SetReadLimit()` immediately after upgrading an HTTP connection to a WebSocket connection.
2. Adding a new `ReadLimit` parameter in the WebSocket server configuration.

Here's a quick overview of the changes:

### Server Configuration Update

A new parameter `ReadLimit` has been introduced under the `[RPC.WebSockets]` configuration:

```toml
[RPC.WebSockets]
    Enabled = true
    Port = 8133
    ReadLimit = 1048576  # This denotes 1 MiB
```

### Reviewers
- @ToniRamirezM 
- @agnusmor 

Codeowner reviewers:
- @tclemos

2023-07-19 12:52 UTC, tclemos requested changes
- We must add tests to make sure we react properly when the read limit is exceeded.
- We must add a new test case for the new default config value.
- Is there an explanation for this value to be `1048576`? We have endpoints that allows the user to send a legit message bigger than this, like `eth_estimateGas` and `eth_call`, I'm not sure if this is a too-tight value, and since the point is to avoid it to be infinite, maybe we could have a bigger value to make sure it is safe but also to avoid unnecessary friction.
- Config example should contain only the new parameter and all the config levels needed to set it, like this:
```toml
[RPC]
	[RPC.WebSockets]
		ReadLimit = 1048576 
```
- also it's important to mention what happens if the parameter is set to `0`, and test it.

2023-07-19 12:52 UTC, tclemos commented on test/config/debug.node.config.toml
> +		ReadLimit = 1048576
this change is not needed, since it is the same value as the default.

2023-07-19 12:52 UTC, tclemos commented on test/config/test.node.config.toml
> +		ReadLimit = 1048576
this change is not needed, since it is the same value as the default.

2023-07-19 12:52 UTC, tclemos commented on config/environments/local/local.node.config.toml
> +		ReadLimit = 1048576
this change is not needed, since it is the same value as the default.

2023-07-19 12:52 UTC, tclemos commented on config/default.go
> +		ReadLimit = 1048576
- a test to the default config should be added.

2023-07-19 13:19 UTC, Psykepro commented on test/config/debug.node.config.toml
> +		ReadLimit = 1048576
Actually, there is no default Read limit. If we don't set it everyone can DDOS the node. But we definitely must set the most reasonable limit.

2023-07-19 13:24 UTC, Psykepro commented
> * We must add tests to make sure we react properly when the read limit is exceeded.
> * We must add a new test case for the new default config value.
> * Is there an explanation for this value to be `1048576`? We have endpoints that allows the user to send a legit message bigger than this, like `eth_estimateGas` and `eth_call`, I'm not sure if this is a too-tight value, and since the point is to avoid it to be infinite, maybe we could have a bigger value to make sure it is safe but also to avoid unnecessary friction.
> * Config example should contain only the new parameter and all the config levels needed to set it, like this:
> 
> ```toml
> [RPC]
> 	[RPC.WebSockets]
> 		ReadLimit = 1048576 
> ```
> 
> * also it's important to mention what happens if the parameter is set to `0`, and test it.

I tested it locally and it reacts properly. But will create Unit test for that no probs. Apart from the for the value I set (1 MB) It's maybe not the best. But why would we need more than 1MB when we have this constraint for the whole batch:
```toml
MaxBatchBytesSize = 120000
````
If someone tries to `eth_estimateGas` for more bytes than 1 MB just for 1 tx this transaction is definitely invalid. Right?

2023-07-24 22:29 UTC, tclemos commented on config/default.go
> +		ReadLimit = 1048576
I've added the test to the PR

2023-07-24 22:37 UTC, tclemos commented
> ```toml
> MaxBatchBytesSize = 120000
> ```
> 
> If someone tries to `eth_estimateGas` for more bytes than 1 MB (which fits almost 10 batches) just for 1 tx this transaction is definitely invalid. Right? Maybe also we can change to use multiplied by 10 the `MaxBatchBytesSize` config value which will be shared config struct from this PR #2298

this makes sense for `eth_estimateGas`, but `eth_call` allow unsigned txs to be executed to get value via read only operations, these operations can have a huge payload.

let's talk with @xavier-romero to see if we can get some metrics from `Mainnet` and `Testnet` to get a better value to avoid causing unnecessary friction.

Probably we can get the average and max size for requests sent to `eth_call` so far to both networks and see if we can define a better number.

Also, the problem at the moment is that we don't have a limit, so the user can open the socket and start sending bytes, this makes the server accumulate these bytes in the memory for this connection until the user defines the message is ready to be read by the server, but with the read limitation, as soon as the message reaches the read limit, the connection is closed and the memory will be free as soon as the GC collects it, theoretically we can support a bigger number safely.

2023-07-25 11:56 UTC, tclemos approved these changes

2023-08-18 12:36 UTC, ToniRamirezM approved these changes

2023-08-21 12:00 UTC, Psykepro commented
@tclemos 
> > ```toml
> > MaxBatchBytesSize = 120000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If someone tries to `eth_estimateGas` for more bytes than 1 MB (which fits almost 10 batches) just for 1 tx this transaction is definitely invalid. Right? Maybe also we can change to use multiplied by 10 the `MaxBatchBytesSize` config value which will be shared config struct from this PR #2298
> 
> this makes sense for `eth_estimateGas`, but `eth_call` allow unsigned txs to be executed to get value via read only operations, these operations can have a huge payload.
> 
> let's talk with @xavier-romero to see if we can get some metrics from `Mainnet` and `Testnet` to get a better value to avoid causing unnecessary friction.
> 
> Probably we can get the average and max size for requests sent to `eth_call` so far to both networks and see if we can define a better number.
> 
> Also, the problem at the moment is that we don't have a limit, so the user can open the socket and start sending bytes, this makes the server accumulate these bytes in the memory for this connection until the user defines the message is ready to be read by the server, but with the read limitation, as soon as the message reaches the read limit, the connection is closed and the memory will be free as soon as the GC collects it, theoretically we can support a bigger number safely.

I've updated the value to 80 MiB based on the Logs metrics for the maximum `body_bytes_size` sent to the `JSON-RPC`, which is `75.24 MiB`

2023-08-22 07:00 UTC, merged