Check flushID != 0 in Sequencer
0xPolygonHermez/zkevm-node pull request #2415
Opened 2023-08-16 18:13 UTC by agnusmor

### What does this PR do?

Adds a check to detect if the flushID received from the executor is 0. It should never be 0 for the Sequencer. If it is 0 it means the executor probably is running in readonly mode (the HashDB is not updated). If the flushid is 0 the Sequencer will stop showing a log.Fatal message

### Reviewers

Main reviewers:
@ToniRamirezM 
@Psykepro 
@ARR552

2023-08-16 19:00 UTC, ToniRamirezM requested changes

2023-08-16 19:00 UTC, ToniRamirezM commented on sequencer/finalizer.go
> +					log.Fatal("storedFlushID is 0. Please check that prover/executor config parameter dbReadOnly is false")
```suggestion
					f.halt(ctx, fmt.Errorf("storedFlushID is 0. Please check that prover/executor config parameter dbReadOnly is false"))					
```

2023-08-17 06:07 UTC, ToniRamirezM approved these changes

2023-08-17 06:50 UTC, ARR552 approved these changes

2023-08-17 13:02 UTC, merged