Improve effective gas price implementation (RPC filter, gasprice/balance opcodes flags, new formula)
0xPolygonHermez/zkevm-node pull request #2690
Opened 2023-10-19 11:15 UTC by agnusmor

Closes #2596 

### What does this PR do?

Do changes in the effective gas price implementation to match redefined process workflow. Check related issue for details

### Reviewers

Main reviewers:

- @ToniRamirezM 
- @joanestebanr 
- @tclemos 
- @Psykepro

2023-10-30 15:05 UTC, ToniRamirezM requested changes

2023-10-30 15:05 UTC, ToniRamirezM commented on pool/pool.go
> +	// Reject transaction if EffetiveGasPrice is enabled
```suggestion
	// Reject transaction if EffectiveGasPrice is enabled
```

2023-10-30 15:05 UTC, ToniRamirezM commented on proto/src/proto/executor/v1/executor.proto
> +    repeated bytes nodes_keys = 19;
???

2023-10-30 15:05 UTC, ToniRamirezM commented on proto/src/proto/executor/v1/executor.proto
> +    repeated bytes program_keys = 20;
???

2023-10-30 15:05 UTC, ToniRamirezM commented on proto/src/proto/executor/v1/executor.proto
> +    string type = 6;
???

2023-10-30 15:05 UTC, ToniRamirezM commented on proto/src/proto/executor/v1/executor.proto
> +    EXECUTOR_ERROR_INVALID_GET_KEY = 80;
The handling of this new error has not been added to /state/runtime/executor/errors.go

2023-10-30 15:05 UTC, ToniRamirezM commented on sequencer/finalizer.go
> +		if !reprocessTx {
Maybe it is better to rename this variable to "firstTXProcess"

2023-10-30 15:05 UTC, ToniRamirezM commented on pool/effectivegasprice.go
> +func (e *EffectiveGasPrice) IsEffectiveGasPriceEnabled() bool {
```suggestion
func (e *EffectiveGasPrice) IsEnabled() bool {
```

2023-10-30 15:05 UTC, ToniRamirezM commented on sequencer/finalizer.go
> +	notFoundFirst := true // used to log debug only the first message when there is no txs to process
The name of this variable does not transmit (at least to me) what it represents

2023-10-30 15:05 UTC, ToniRamirezM commented on state/types.go
> +	Reprocess      bool
```suggestion
	NeedsReprocess      bool
```

2023-10-30 15:58 UTC, agnusmor commented on sequencer/finalizer.go
> +		if !reprocessTx {
ok

2023-10-30 15:58 UTC, agnusmor commented on pool/effectivegasprice.go
> +func (e *EffectiveGasPrice) IsEffectiveGasPriceEnabled() bool {
It's true!

2023-10-30 16:00 UTC, agnusmor commented on state/types.go
> +	Reprocess      bool
I undertand that using "re" prefix means that you do a second process, maybe "reprocessed"?

2023-10-31 08:16 UTC, ToniRamirezM approved these changes

2023-10-31 09:13 UTC, merged