review Estimate Gas validations and Formulas
0xPolygonHermez/zkevm-node pull request #2856
Opened 2023-11-28 19:08 UTC by tclemos

Closes #2848.

### What does this PR do?

review Estimate Gas validations and Formulas

2023-11-30 09:10 UTC, krlosMata requested changes

2023-11-30 09:10 UTC, krlosMata commented on state/state.go
> +	DefaultSenderAddress = "0x1111111111111111111111111111111111111111"
Maybe we can set here what geth does and use the `ZeroAddress`.
Then, if the `from` is unspecified, we set the from to `ZeroAddress`.

2023-11-30 09:10 UTC, krlosMata commented on state/transaction.go
>  		senderBalance, err := s.tree.GetBalance(ctx, senderAddress, stateRoot.Bytes())
This check should be done even if `from` is not specified. It will be done with the `defaultAddress`

2023-11-30 09:10 UTC, krlosMata commented on state/transaction.go
> +		// check if the account balance is at least bigger than the tx Value
available balance to send `value` should be check for `defaultAdress` & if the `gasPrice` is not set as well

2023-12-01 12:10 UTC, ARR552 approved these changes
LGTM

2023-12-01 19:58 UTC, merged